[project]
name = "navsuite"
version = "0.1.0"
description = ""
authors = [{ name = "Tanner Koza", email = "kozatanner@gmail.com" }]
dependencies = ["navtools", "navsim", "navgnss", "navplot"]
readme = "README.md"
requires-python = ">= 3.10"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/*"]

[tool.uv.workspace]
members = ["src/*"]

[tool.uv.sources]
navtools = { workspace = true }
navsim = { workspace = true }
navgnss = { workspace = true }
navplot = { workspace = true }

[dependency-groups]
dev = [
    "pre-commit>=3.8.0",
    "pytest>=8.3.2",
    "mypy>=1.11.1",
    "pytest-cov>=5.0.0",
    "snakeviz>=2.2.2",
    "matplotlib>=3.10.3",
    "pyqt6>=6.9.1",
    "junit2html>=31.0.2",
]

[[tool.mypy.overrides]]
module = "numba"
ignore_missing_imports = true
