[project]
name = "navsim"
version = "0.1.0"
description = "Add your description here"
authors = [{ name = "Tanner Koza", email = "kozatanner@gmail.com" }]
dependencies = [
    "navtools @ git+https://github.com/tannerkoza/navsuite.git#subdirectory=src/navtools",
    "navgnss @ git+https://github.com/tannerkoza/navsuite.git#subdirectory=src/navgnss",
    "sgp4>=2.24",
    "tqdm>=4.67.1",
    "astropy>=6.1.7",
    "scipy>=1.15.3",
    "tomli>=2.2.1",
]
readme = "README.md"
requires-python = ">= 3.10"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
navsim = "navsim:simulate"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/navsim"]
