[project]
name = "navsim"
version = "0.1.0"
description = "A Python satellite navigation simulator package within the navsuite collection of navigation-related tools."
readme = "README.md"
authors = [{ name = "Tanner Koza", email = "kozatanner@gmail.com" }]
requires-python = ">= 3.10"
dependencies = [
    "navtools @ git+https://github.com/tannerkoza/navsuite.git#subdirectory=src/navtools",
    "navgnss @ git+https://github.com/tannerkoza/navsuite.git#subdirectory=src/navgnss",
    "sgp4>=2.24",
    "tqdm>=4.67.1",
    "astropy>=6.1.7",
    "scipy>=1.15.3",
    "tomli>=2.2.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
navsim = "navsim:main"

[tool.setuptools.package-data]
navsim = ["config/*", "trajectories/*"]

[tool.hatch.build.targets.wheel]
packages = ["src/navsim"]

[tool.hatch.metadata]
allow-direct-references = true
