# Date & Time
initial_datetime=2025-07-02T16:11:00-06:00
duration=3600 # [s]
fsim=1 # [Hz]

# Trajectory
trajectory_name="daytona_500_sdx_1s_loop"

# # Constellations
# [[constellation]]
# reference_constellation="starlink"
# signals="test_signal"
# mask_angle= 30 # [deg]

# [[constellation]]
# reference_constellation="iridium"
# signals="test_signal"
# mask_angle=10 # [deg]

[[constellation]]
reference_constellation="gps"
signals="test_signal"
mask_angle=10 # [deg]

[[constellation]]
reference_constellation="beidou"
signals="test_signal"
mask_angle=10 # [deg]