[project]
name = "navtools"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Tanner Koza", email = "kozatanner@gmail.com" }
]
dependencies = [
    "numba>=0.61.2",
    "requests>=2.32.4",
    "unlzw3>=0.2.3",
    "aspn23 @ git+https://github.com/tannerkoza/aspn-python.git@main#subdirectory=aspn-py",
    "aspn23-lcm @ git+https://github.com/tannerkoza/aspn-python.git@main#subdirectory=aspn-lcm",
    "prompt-toolkit>=3.0.51",
    "types-requests>=2.32.4.20250611",
]
readme = "README.md"
requires-python = ">= 3.10"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/navtools"]
