[project]
name = "navtools"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Tanner Koza", email = "kozatanner@gmail.com" }
]
dependencies = [
    # firehose-outputs main branch - committed 12 June 2025
    "aspn23 @ git+ssh://git@git.aspn.us/pntos/firehose-outputs.git@d425e26330e62371038f14ad12a8d8b4374698a6#subdirectory=aspn-py",
    # firehose-outputs main branch - committed 26 June 2025
    "aspn23_lcm @ git+ssh://git@git.aspn.us/pntos/firehose-outputs.git@50b596d2c349ceb98b60ab6aecc91961424bcec8#subdirectory=lcm/python",
    "numba>=0.61.2",
    "requests>=2.32.4",
    "unlzw3>=0.2.3",
]
readme = "README.md"
requires-python = ">= 3.10"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/navtools"]
