[project]
name = "navgnss"
version = "0.1.0"
description = "A Python satellite navigation algorithm package within the navsuite collection of navigation-related tools."
readme = "README.md"
authors = [{ name = "Tanner Koza", email = "kozatanner@gmail.com" }]
requires-python = ">= 3.10"

dependencies = [
    "navtools @ git+https://github.com/tannerkoza/navsuite.git#subdirectory=src/navtools",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/navgnss"]
