name: Pre-Commit & Type Checking

on: 
  - push
  - pull_request

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4
      - uses: eifinger/setup-rye@v4
        id: setup-rye
        with:
          enable-cache: true
          cache-prefix: ${{ matrix.python-version }}

      - name: Pin python-version ${{ matrix.python-version }}
        run: rye pin ${{ matrix.python-version }}

      - name: Install dependencies
        if: steps.setup-rye.outputs.cache-hit != 'true'
        run: |
          rye sync

      - name: Cache pre-commit
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9  # v4.0.2
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-|${{ matrix.python-version }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit hooks
        run: |
          rye run pre-commit run --all-files

      - name: Run mypy
        run: |
          rye run mypy src/ tests/ --install-types --non-interactive --ignore-missing-imports

      - name: Commit changes
        if: always()
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Apply pre-commit changes'
          add: '*.py'
